# Generated by Django 4.2 on 2023-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_order_is_finalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default=0.0),
        ),
    ]
